service: pontte-calculator-recalc
frameworkVersion: ">=2 || <3"

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: '20201221'

functions:
  calculate:
    handler: src/__main__.handle
    events:
      - httpApi:
          path: /
          method: post
