service: aws-python-http-api
frameworkVersion: 2

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
