jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@3c9b0fc6f2d223b8450b02a0445f526350fc73e0
        with:
          key: ${{ secrets.GH_ACTIONS_SSH_KEY }}
          known_hosts: unnecessary
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: channel:nixos-unstable
      - name: Pre Build
        run: nix develop --command gh-actions-ci-cd-pre-build
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        name: Deploy
        run: nix develop --command gh-actions-ci-cd-deploy
      - name: Post Deploy
        run: nix develop --command gh-actions-ci-cd-post-deploy
"on":
  push:
    branches:
      - master
      - staging
    paths:
      - src/**
